# Based on https://github.com/pantsbuild/pex/blob/master/.travis.yml
#
# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines".
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
dist: xenial

# TRAVIS_PYTHON_VERSION

matrix:
  include:
    - language: python
      python: "2.7"
      env: TOXENV=py27-flake8

    - language: python
      python: "2.7"
      env: TOXENV=py27-ansible24

    - language: python
      python: "2.7"
      env: TOXENV=py27-ansible25

    - language: python
      python: "2.7"
      env: TOXENV=py27-ansible26

    - language: python
      python: "2.7"
      env: TOXENV=py27-ansible27

    - language: python
      python: "2.7"
      env: TOXENV=py27-ansible28

    - language: python
      python: "2.7"
      env: TOXENV=py27-ansibledevel


    - language: python
      python: "3.7"
      env: TOXENV=py37-ansible24

    - language: python
      python: "3.7"
      env: TOXENV=py37-ansible25

    - language: python
      python: "3.7"
      env: TOXENV=py37-ansible26

    - language: python
      python: "3.7"
      env: TOXENV=py37-ansible27

    - language: python
      python: "3.7"
      env: TOXENV=py37-ansible28

    - language: python
      python: "3.7"
      env: TOXENV=py37-ansibledevel

    - language: python
      python: "3.7"
      env: TOXENV=py37-flake8

install:
  - pip install -r test-deps.txt

script:
- tox -v
